<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-OB1OE1J" name="com.nitara.HealthManagement.DeleteFollowUp" tests="1" failures="0" timestamp="2022-02-22T19:53:59 IST" time="48.919" errors="1">
  <testcase name="FollowUp_ViewData" time="48.919" classname="com.nitara.HealthManagement.DeleteFollowUp">
    <error type="java.lang.NoClassDefFoundError" message="Lgroovy/lang/Tuple2;">
      <![CDATA[java.lang.NoClassDefFoundError: Lgroovy/lang/Tuple2;
at java.lang.Class.getDeclaredFields0(Native Method)
at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
at java.lang.Class.getDeclaredFields(Class.java:1916)
at org.codehaus.groovy.reflection.CachedClass$1$1.run(CachedClass.java:48)
at java.security.AccessController.doPrivileged(Native Method)
at org.codehaus.groovy.reflection.CachedClass$1.initValue(CachedClass.java:45)
at org.codehaus.groovy.reflection.CachedClass$1.initValue(CachedClass.java:43)
at org.codehaus.groovy.util.LazyReference.getLocked(LazyReference.java:46)
at org.codehaus.groovy.util.LazyReference.get(LazyReference.java:33)
at org.codehaus.groovy.reflection.CachedClass.getFields(CachedClass.java:254)
at groovy.lang.MetaClassImpl.addFields(MetaClassImpl.java:2363)
at groovy.lang.MetaClassImpl.inheritFields(MetaClassImpl.java:2358)
at groovy.lang.MetaClassImpl.setupProperties(MetaClassImpl.java:2248)
at groovy.lang.MetaClassImpl.addProperties(MetaClassImpl.java:3255)
at groovy.lang.MetaClassImpl.initialize(MetaClassImpl.java:3226)
at org.codehaus.groovy.reflection.ClassInfo.getMetaClassUnderLock(ClassInfo.java:210)
at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:241)
at io.restassured.internal.ResponseSpecificationImpl.$getStaticMetaClass(ResponseSpecificationImpl.groovy)
at io.restassured.internal.ResponseSpecificationImpl.<init>(ResponseSpecificationImpl.groovy:52)
at io.restassured.internal.ResponseSpecificationImpl.<init>(ResponseSpecificationImpl.groovy:67)
at io.restassured.RestAssured.createTestSpecification(RestAssured.java:1510)
at io.restassured.RestAssured.given(RestAssured.java:711)
at com.nitara.APIFunctions.LoginAPI.API_SPLogin(LoginAPI.java:23)
at com.nitara.APIFunctions.AddFollowUpAPI.addFollowUpDetails(AddFollowUpAPI.java:19)
at com.nitara.HealthManagement.DeleteFollowUp.FollowUp_ViewData(DeleteFollowUp.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.ClassNotFoundException: groovy.lang.Tuple2
at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
... 53 more
]]>
    </error>
  </testcase> <!-- FollowUp_ViewData -->
  <system-out/>
</testsuite> <!-- com.nitara.HealthManagement.DeleteFollowUp -->
